image: atlassian/default-image:2
pipelines:
  branches:   
    quality:
      - step:
          name: Build and Deploy to Production
          trigger: automatic
          deployment: staging
          caches:
            - maven
            - pip
          script: # Modify the commands below to build your repository.
            - apt-get update && apt-get install -y python3 python3-pip
            - mvn package # -B batch mode makes Maven less verbose
            - pip3 install boto3==1.3.0
            - python3 lambda_deploy_quality.py

          artifacts:
            - target/demo-0.0.1.jar